# Generated by Django 3.2.3 on 2023-10-23 21:35

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('passing', 'Проходит обучение'), ('academic_leave', 'Академический отпуск'), ('graduate', 'Выпускник'), ('expelled', 'Отчислен')], max_length=150, verbose_name='Учебный статус')),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=20, region=None, unique=True, verbose_name='Номер телефона')),
                ('alternate_email', models.EmailField(max_length=254, unique=True, verbose_name='Дополнительный адрес электронной почты')),
                ('telegram_login', models.CharField(blank=True, max_length=100, null=True, verbose_name='Логин в Telegram')),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('job_search', 'Ищу работу'), ('employed', 'Трудоустроен'), ('internship_search', 'В поиске стажировки'), ('other', 'Другое')], max_length=100, verbose_name='Статус трудоустройства')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('frontend_dev', 'Фронтенд-разработчик'), ('fullstack_dev', 'Фулстек-разработчик'), ('python_dev', 'Python-разработчик'), ('qa_engineer', 'Инженер по тестированию'), ('java_dev', 'Java-разработчик'), ('data_scientist', 'Специалист по data-science')], max_length=100, verbose_name='Должность')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Навык')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StudentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('education_level', models.CharField(blank=True, choices=[('school', 'Среднее образование'), ('college', 'Средне-специальное образование'), ('university', 'Высшее образование'), ('postgrad', 'Ученая степень')], max_length=100, null=True, verbose_name='Уровень образования')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('work_experience', models.CharField(blank=True, max_length=100, null=True, verbose_name='Опыт работы')),
                ('grade', models.CharField(blank=True, choices=[('junior', 'Junior'), ('middle', 'Middle')], max_length=100, null=True, verbose_name='Грэйд')),
                ('description', models.TextField(blank=True, null=True, verbose_name='О себе')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos/', verbose_name='Фото')),
                ('resume', models.FileField(blank=True, null=True, upload_to='student_resumes/', verbose_name='Резюме')),
                ('academic_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.academicstatus', verbose_name='Учебный статус')),
                ('contact_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.contactinfo', verbose_name='Контактная информация')),
                ('employment_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.employmentstatus', verbose_name='Статус трудоустройства')),
                ('skills', models.ManyToManyField(blank=True, related_name='students', to='students.Skill', verbose_name='Навыки')),
                ('training_status', models.ManyToManyField(blank=True, through='students.StudentPosition', to='students.Position', verbose_name='Предпочтительные должности')),
            ],
        ),
    ]
