# Generated by Django 3.2.3 on 2023-10-28 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('no_experience', 'Нет опыта'), ('1_to_3_years', 'От 1 года до 3 лет'), ('3_to_6_years', 'От 3 до 6 лет'), ('more_than_6_years', 'Более 6 лет')], help_text='Выберите опыт работы студента.', max_length=100, verbose_name='Опыт работы')),
            ],
            options={
                'verbose_name': 'Опыт работы',
                'verbose_name_plural': 'Опыт работы',
            },
        ),
        migrations.AddField(
            model_name='studentresume',
            name='experience',
            field=models.ForeignKey(blank=True, help_text='Выберите опыт работы студента (при наличии).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.experience', verbose_name='Опыт работы'),
        ),
    ]
