# Generated by Django 3.2.3 on 2023-10-23 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentposition',
            name='academic_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.academicstatus', verbose_name='Учебный статус'),
        ),
        migrations.AddField(
            model_name='studentposition',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.position', verbose_name='Позиция'),
        ),
        migrations.AddField(
            model_name='studentposition',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_positions', to='students.studentuser', verbose_name='Студент'),
        ),
    ]
