# Generated by Django 3.2.3 on 2023-10-25 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20231024_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('junior', 'Junior'), ('middle', 'Middle')], max_length=100, verbose_name='Грейд')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Местоположение')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('no_experience', 'Нет опыта'), ('1_to_3_years', 'От 1 года до 3 лет'), ('3_to_6_years', 'От 3 до 6 лет'), ('more_than_6_years', 'Более 6 лет')], max_length=100, verbose_name='Опыт работы')),
            ],
        ),
        migrations.AlterModelOptions(
            name='academicstatus',
            options={'verbose_name': 'Академический статус', 'verbose_name_plural': 'Академические статусы'},
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='employmentstatus',
            options={'verbose_name': 'Статус трудоустройства', 'verbose_name_plural': 'Статусы трудоустройства'},
        ),
        migrations.AlterModelOptions(
            name='favoriteresume',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранные резюме'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Ожидаемая должность', 'verbose_name_plural': 'Ожидаемые должности'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Навык', 'verbose_name_plural': 'Навыки'},
        ),
        migrations.AlterModelOptions(
            name='studentresume',
            options={'verbose_name': 'Резюме', 'verbose_name_plural': 'Резюме'},
        ),
        migrations.RemoveField(
            model_name='studentresume',
            name='city',
        ),
        migrations.AlterField(
            model_name='academicstatus',
            name='name',
            field=models.CharField(choices=[('student', 'Студент'), ('academic_leave', 'Академический отпуск'), ('graduate', 'Выпускник'), ('expelled', 'Отчислен')], max_length=150),
        ),
        migrations.AlterField(
            model_name='employmentstatus',
            name='name',
            field=models.CharField(choices=[('job_search', 'Ищу работу'), ('employed', 'Трудоустроен'), ('internship_search', 'В поиске стажировки'), ('other', 'Другое')], max_length=100),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(choices=[('frontend_dev', 'Фронтенд-разработчик'), ('fullstack_dev', 'Фулстек-разработчик'), ('python_dev', 'Python-разработчик'), ('qa_engineer', 'Инженер по тестированию'), ('java_dev', 'Java-разработчик'), ('data_scientist', 'Специалист по data-science')], max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='studentresume',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.location'),
        ),
        migrations.AlterField(
            model_name='studentresume',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.grade'),
        ),
        migrations.AlterField(
            model_name='studentresume',
            name='work_experience',
            field=models.ForeignKey(blank=True, default='no_experience', null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.workexperience'),
        ),
    ]
