# Generated by Django 3.2.3 on 2023-10-25 20:08

from django.db import migrations, models
import students.utils


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20231025_0843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': 'Грейд', 'verbose_name_plural': 'Грейды'},
        ),
        migrations.AlterModelOptions(
            name='workexperience',
            options={'verbose_name': 'Опыт работы', 'verbose_name_plural': 'Опыт работы'},
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentresume',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=students.utils.student_photo_upload, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='studentresume',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=students.utils.student_resume_upload, verbose_name='Резюме'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='name',
            field=models.CharField(choices=[('no_experience', 'Нет опыта'), ('1_to_3_years', 'От 1 года до 3 лет'), ('3_to_6_years', 'От 3 до 6 лет'), ('more_than_6_years', 'Более 6 лет')], max_length=100),
        ),
    ]
