# Generated by Django 3.2.3 on 2023-10-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20231025_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresume',
            name='has_higher_education',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentresume',
            name='has_participated_in_hackathons',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentresume',
            name='has_personal_projects',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentresume',
            name='has_video_presentation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentresume',
            name='skills_verified',
            field=models.BooleanField(default=False),
        ),
    ]
