# Generated by Django 3.2.3 on 2023-10-26 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import students.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0006_auto_20231025_2354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Местоположение', 'verbose_name_plural': 'Местоположения'},
        ),
        migrations.AlterField(
            model_name='academicstatus',
            name='name',
            field=models.CharField(choices=[('student', 'Студент'), ('academic_leave', 'Академический отпуск'), ('graduate', 'Выпускник'), ('expelled', 'Отчислен')], help_text='Выберите академический статус студента.', max_length=150, verbose_name='Академический статус'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='alternate_email',
            field=models.EmailField(help_text='Укажите дополнительный адрес электронной почты студента.', max_length=254, unique=True, verbose_name='Дополнительный адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Укажите номер телефона студента.', max_length=20, region=None, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='telegram_login',
            field=models.CharField(blank=True, help_text='Укажите логин студента в Telegram (при наличии).', max_length=100, null=True, verbose_name='Логин в Telegram'),
        ),
        migrations.AlterField(
            model_name='employmentstatus',
            name='name',
            field=models.CharField(choices=[('job_search', 'Ищу работу'), ('employed', 'Трудоустроен'), ('internship_search', 'В поиске стажировки'), ('other', 'Другое')], help_text='Выберите статус трудоустройства студента.', max_length=100, verbose_name='Статус трудоустройства'),
        ),
        migrations.AlterField(
            model_name='favoriteresume',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата, когда резюме было добавлено в избранное.', verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='favoriteresume',
            name='resume',
            field=models.ForeignKey(help_text='Выберите резюме, добавляемое в избранное.', on_delete=django.db.models.deletion.CASCADE, related_name='favorited_resumes', to='students.studentresume', verbose_name='Избранное резюме'),
        ),
        migrations.AlterField(
            model_name='favoriteresume',
            name='user',
            field=models.ForeignKey(help_text='Выберите пользователя, который добавляет резюме в избранное.', on_delete=django.db.models.deletion.CASCADE, related_name='favorite_by', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(choices=[('junior', 'Junior'), ('middle', 'Middle')], help_text='Выберите грейд студента.', max_length=100, verbose_name='Грейд'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(help_text='Введите наименование местоположения.', max_length=100, verbose_name='Наименование местоположения'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(choices=[('frontend_dev', 'Фронтенд-разработчик'), ('fullstack_dev', 'Фулстек-разработчик'), ('python_dev', 'Python-разработчик'), ('qa_engineer', 'Инженер по тестированию'), ('java_dev', 'Java-разработчик'), ('data_scientist', 'Специалист по data-science')], help_text='Выберите ожидаемую должность студента.', max_length=100, verbose_name='Ожидаемая должность'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(help_text='Введите наименование навыка.', max_length=100, verbose_name='Наименование навыка'),
        ),
        migrations.AlterField(
            model_name='studentposition',
            name='academic_status',
            field=models.ForeignKey(blank=True, help_text='Выберите учебный статус студента (при наличии).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.academicstatus', verbose_name='Учебный статус'),
        ),
        migrations.AlterField(
            model_name='studentposition',
            name='position',
            field=models.ForeignKey(help_text='Выберите позицию для связи с студентом.', on_delete=django.db.models.deletion.CASCADE, to='students.position', verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='studentposition',
            name='student',
            field=models.ForeignKey(help_text='Выберите студента для связи с позицией.', on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='students.studentresume', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='studentresume',
            name='academic_status',
            field=models.ForeignKey(blank=True, help_text='Выберите учебный статус студента (при наличии).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.academicstatus', verbose_name='Учебный статус'),
        ),
        migrations.AlterField(
            model_name='studentresume',
            name='contact_info',
            field=models.OneToOneField(help_text='Выберите контактную информацию для профиля студента.', on_delete=django.db.models.deletion.CASCADE, to='students.contactinfo', verbose_name='Контактная информация'),
        ),
        migrations.AlterField(
            model_name='studentresume',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Укажите дату рождения студента (при наличии).', null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='studentresume',
            name='description',
            field=models.TextField(blank=True, help_text='Введите описание студента (при наличии).', null=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='studentresume',
            name='education_level',
            field=models.CharField(blank=True, choices=[('school', 'Среднее образование'), ('college', 'Средне-специальное образование'), ('university', 'Высшее образование'), ('postgrad', 'Ученая степень')], help_text='Выберите уровень образования студента (при наличии).', max_length=100, null=True, verbose_name='Уровень образования'),
        ),
        migrations.AlterField(
            model_name='studentresume',
            name='employment_status',
            field=models.ForeignKey(blank=True, help_text='Выберите статус трудоустройства студента (при наличии).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.employmentstatus', verbose_name='Статус трудоустройства'),
        ),
        migrations.AlterField(
            model_name='studentresume',
            name='grade',
            field=models.ForeignKey(blank=True, help_text='Выберите грейд студента (при наличии).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.grade', verbose_name='Грейд'),
        ),
        migrations.AlterField(
            model_name='studentresume',
            name='has_higher_education',
            field=models.BooleanField(default=False, help_text='Укажите, имеет ли студент высшее образование.', verbose_name='Высшее образование'),
        ),
        migrations.AlterField(
            model_name='studentresume',
            name='has_participated_in_hackathons',
            field=models.BooleanField(default=False, help_text='Укажите, участвовал ли студент в хакатонах.', verbose_name='Участие в хакатонах'),
        ),
        migrations.AlterField(
            model_name='studentresume',
            name='has_personal_projects',
            field=models.BooleanField(default=False, help_text='Укажите, есть ли у студента пет-проекты.', verbose_name='Наличие пет-проектов'),
        ),
        migrations.AlterField(
            model_name='studentresume',
            name='has_video_presentation',
            field=models.BooleanField(default=False, help_text='Укажите, есть ли у студента видео-презентация.', verbose_name='С видео-презентацией'),
        ),
        migrations.AlterField(
            model_name='studentresume',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Выберите местоположение студента (при наличии).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.location', verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='studentresume',
            name='photo',
            field=models.ImageField(blank=True, help_text='Загрузите фотографию студента (при наличии).', null=True, upload_to=students.utils.student_photo_upload, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='studentresume',
            name='resume',
            field=models.FileField(blank=True, help_text='Загрузите резюме студента (при наличии).', null=True, upload_to=students.utils.student_resume_upload, verbose_name='Резюме'),
        ),
        migrations.AlterField(
            model_name='studentresume',
            name='skills',
            field=models.ManyToManyField(blank=True, help_text='Выберите навыки, связанные с профилем студента (при наличии).', related_name='students', to='students.Skill', verbose_name='Навыки'),
        ),
        migrations.AlterField(
            model_name='studentresume',
            name='skills_verified',
            field=models.BooleanField(default=False, help_text='Укажите, подтверждены ли навыки студента.', verbose_name='Навыки подтверждены'),
        ),
        migrations.AlterField(
            model_name='studentresume',
            name='training_status',
            field=models.ManyToManyField(blank=True, help_text='Выберите предпочтительные должности для студента (при наличии).', through='students.StudentPosition', to='students.Position', verbose_name='Предпочтительные должности'),
        ),
        migrations.AlterField(
            model_name='studentresume',
            name='user',
            field=models.OneToOneField(help_text='Выберите пользователя и свяжите его с профилем студента.', on_delete=django.db.models.deletion.CASCADE, related_name='student_resume', to=settings.AUTH_USER_MODEL, verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='studentresume',
            name='work_experience',
            field=models.ForeignKey(blank=True, default='no_experience', help_text='Выберите опыт работы студента (при наличии).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.workexperience', verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='name',
            field=models.CharField(choices=[('no_experience', 'Нет опыта'), ('1_to_3_years', 'От 1 года до 3 лет'), ('3_to_6_years', 'От 3 до 6 лет'), ('more_than_6_years', 'Более 6 лет')], help_text='Выберите опыт работы студента.', max_length=100, verbose_name='Опыт работы'),
        ),
    ]
