# Generated by Django 3.2.3 on 2023-10-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20231027_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentposition',
            name='academic_status',
        ),
        migrations.RemoveField(
            model_name='studentposition',
            name='position',
        ),
        migrations.RemoveField(
            model_name='studentposition',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentresume',
            name='training_status',
        ),
        migrations.AddField(
            model_name='studentresume',
            name='achievement',
            field=models.CharField(blank=True, help_text='Укажите свои достижения (при наличии).', max_length=50, null=True, verbose_name='Достижения'),
        ),
        migrations.AddField(
            model_name='studentresume',
            name='portfolio',
            field=models.URLField(blank=True, help_text='Прикрепите ссылку на портфолио (при наличии).', null=True, verbose_name='Портфолио'),
        ),
        migrations.AddField(
            model_name='studentresume',
            name='viewed',
            field=models.BooleanField(default=False, verbose_name='Отметка о просмотре'),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.DeleteModel(
            name='StudentPosition',
        ),
    ]
