version: '3.8'

volumes:
  pg_data:
  media:
  static:


services:
  db:
    image: postgres:16.0
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - ../.env

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    volumes:
      - static:/backend_static/static/

  nginx:
    image: nginx:1.25.3-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - static:/var/html/static/
      - media:/var/html/media/
