swagger: '2.0'
info:
  title: Career-Tracker
  description: Описание
  version: v1
host: 127.0.0.1:8003
schemes:
  - http
basePath: /api/v1
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  Basic:
    type: basic
security:
  - Basic: []
paths:
  /auth/token/login/:
    post:
      operationId: auth_token_login_create
      description: Используется для авторизации по емейлу и паролю, чтобы далее использовать токен при запросах.
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/TokenCreate'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/TokenCreate'
      tags:
        - Авторизация
    parameters: []
  /auth/token/logout/:
    post:
      operationId: auth_token_logout_create
      description: Удаляет токен текущего пользователя
      parameters: []
      responses:
        '201':
          description: ''
      tags:
        - Авторизация
    parameters: []
  /filters/:
    get:
      operationId: filters_list
      description: 'Список доступных фильтров'
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - Фильтры
    parameters: []
  /resume/:
    get:
      operationId: resume_list
      description: 'Получить список всех резюме'
      parameters:
        - name: ordering
          in: query
          description: Which field to use when ordering the results.
          required: false
          type: string
        - name: Номер страницы.
          in: query
          description: A page number within the paginated result set.
          required: false
          type: integer
      responses:
        '200':
          description: ''
          schema:
            required:
              - count
              - results
            type: object
            properties:
              count:
                type: integer
              next:
                type: string
                format: uri
                x-nullable: true
              previous:
                type: string
                format: uri
                x-nullable: true
              results:
                type: array
                items:
                  $ref: '#/definitions/StudentUser'
      tags:
        - Резюме
  /resume/{id}/:
    get:
      operationId: resume_read
      description: 'Получение резюме'
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/StudentUser'
      tags:
        - Резюме

  /users/:
    get:
      operationId: users_list
      description: Представление для работы с публичными данными пользователей.
      parameters:
        - name: page
          in: query
          description: A page number within the paginated result set.
          required: false
          type: integer
      responses:
        '200':
          description: ''
          schema:
            required:
              - count
              - results
            type: object
            properties:
              count:
                type: integer
              next:
                type: string
                format: uri
                x-nullable: true
              previous:
                type: string
                format: uri
                x-nullable: true
              results:
                type: array
                items:
                  $ref: '#/definitions/User'
      tags:
        - Пользователи (HR)
    post:
      operationId: users_create
      description: Представление для работы с публичными данными пользователей.
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/UserCreatePasswordRetype'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/UserCreatePasswordRetype'
      tags:
        - Пользователи (HR)
    parameters: []
  /users/activation/:
    post:
      operationId: users_activation
      description: Представление для работы с публичными данными пользователей.
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/Activation'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/Activation'
      tags:
        - Пользователи (HR)
    parameters: []
  /users/me/:
    get:
      operationId: users_me_read
      description: Представление для работы с публичными данными пользователей.
      parameters:
        - name: page
          in: query
          description: A page number within the paginated result set.
          required: false
          type: integer
      responses:
        '200':
          description: ''
          schema:
            required:
              - count
              - results
            type: object
            properties:
              count:
                type: integer
              next:
                type: string
                format: uri
                x-nullable: true
              previous:
                type: string
                format: uri
                x-nullable: true
              results:
                type: array
                items:
                  $ref: '#/definitions/User'
      tags:
        - Пользователи (HR)
    put:
      operationId: users_me_update
      description: Представление для работы с публичными данными пользователей.
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/User'
      tags:
        - Пользователи (HR)
    patch:
      operationId: users_me_partial_update
      description: Представление для работы с публичными данными пользователей.
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/User'
      tags:
        - Пользователи (HR)
    delete:
      operationId: users_me_delete
      description: Представление для работы с публичными данными пользователей.
      parameters: []
      responses:
        '204':
          description: ''
      tags:
        - Пользователи (HR)
    parameters: []
  /users/resend_activation/:
    post:
      operationId: users_resend_activation
      description: Представление для работы с публичными данными пользователей.
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/SendEmailReset'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/SendEmailReset'
      tags:
        - Пользователи (HR)
    parameters: []
  /users/reset_email/:
    post:
      operationId: users_reset_username
      description: Представление для работы с публичными данными пользователей.
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/SendEmailReset'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/SendEmailReset'
      tags:
        - Пользователи (HR)
    parameters: []
  /users/reset_email_confirm/:
    post:
      operationId: users_reset_username_confirm
      description: Представление для работы с публичными данными пользователей.
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/UsernameResetConfirm'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/UsernameResetConfirm'
      tags:
        - Пользователи (HR)
    parameters: []
  /users/reset_password/:
    post:
      operationId: users_reset_password
      description: Представление для работы с публичными данными пользователей.
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/SendEmailReset'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/SendEmailReset'
      tags:
        - Пользователи (HR)
    parameters: []
  /users/reset_password_confirm/:
    post:
      operationId: users_reset_password_confirm
      description: Представление для работы с публичными данными пользователей.
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/PasswordResetConfirm'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/PasswordResetConfirm'
      tags:
        - Пользователи (HR)
    parameters: []
  /users/set_email/:
    post:
      operationId: users_set_username
      description: Представление для работы с публичными данными пользователей.
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/SetUsername'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/SetUsername'
      tags:
        - Пользователи (HR)
    parameters: []
  /users/set_password/:
    post:
      operationId: users_set_password
      description: Представление для работы с публичными данными пользователей.
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/SetPasswordRetype'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/SetPasswordRetype'
      tags:
        - Пользователи (HR)
    parameters: []
  /users/{id}/:
    get:
      operationId: users_read
      description: Представление для работы с публичными данными пользователей.
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/User'
      tags:
        - Пользователи (HR)
    put:
      operationId: users_update
      description: Представление для работы с публичными данными пользователей.
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/User'
      tags:
        - Пользователи (HR)
    patch:
      operationId: users_partial_update
      description: Представление для работы с публичными данными пользователей.
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/User'
      tags:
        - Пользователи (HR)
    delete:
      operationId: users_delete
      description: Представление для работы с публичными данными пользователей.
      parameters: []
      responses:
        '204':
          description: ''
      tags:
        - Пользователи (HR)
    parameters:
      - name: id
        in: path
        description: A unique integer value identifying this Пользователь.
        required: true
        type: integer
definitions:
  TokenCreate:
    type: object
    properties:
      password:
        title: Password
        type: string
        minLength: 1
      email:
        title: Email
        type: string
        minLength: 1
  StudentPosition:
    type: object
    properties:
      id:
        title: ID
        type: integer
        readOnly: true
      position_name:
        title: Position name
        type: string
        readOnly: true
      academic_status_name:
        title: Academic status name
        type: string
        readOnly: true
  Location:
    type: object
    properties: {}
  WorkExperience:
    type: object
    properties: {}
  Grade:
    type: object
    properties: {}
  ContactInfo:
    required:
      - phone_number
      - alternate_email
    type: object
    properties:
      phone_number:
        title: Номер телефона
        type: string
        maxLength: 20
        minLength: 1
      alternate_email:
        title: Дополнительный адрес электронной почты
        type: string
        format: email
        maxLength: 254
        minLength: 1
      telegram_login:
        title: Логин в Telegram
        type: string
        maxLength: 100
        x-nullable: true
  AcademicStatus:
    type: object
    properties: {}
  EmploymentStatus:
    type: object
    properties: {}
  Skill:
    type: object
    properties: {}
  StudentUser:
    required:
      - user_id
      - username
      - first_name
      - last_name
      - email
      - training_status
      - location
      - work_experience
      - grade
      - contact_info
      - academic_status
      - employment_status
      - skills
    type: object
    properties:
      user_id:
        title: User id
        type: integer
      username:
        title: Username
        type: string
        minLength: 1
      first_name:
        title: First name
        type: string
        minLength: 1
      last_name:
        title: Last name
        type: string
        minLength: 1
      email:
        title: Email
        type: string
        format: email
        minLength: 1
      photo:
        title: Photo
        type: string
        readOnly: true
        format: uri
      training_status:
        type: array
        items:
          $ref: '#/definitions/StudentPosition'
      date_of_birth:
        title: Дата рождения
        type: string
        format: date
        x-nullable: true
      education_level:
        title: Уровень образования
        type: string
        enum:
          - school
          - college
          - university
          - postgrad
        x-nullable: true
      location:
        $ref: '#/definitions/Location'
      work_experience:
        $ref: '#/definitions/WorkExperience'
      grade:
        $ref: '#/definitions/Grade'
      description:
        title: О себе
        type: string
        x-nullable: true
      resume:
        title: Резюме
        type: string
        readOnly: true
        x-nullable: true
        format: uri
      contact_info:
        $ref: '#/definitions/ContactInfo'
      academic_status:
        $ref: '#/definitions/AcademicStatus'
      employment_status:
        $ref: '#/definitions/EmploymentStatus'
      skills:
        type: array
        items:
          $ref: '#/definitions/Skill'
      has_higher_education:
        title: Высшее образование
        type: boolean
      has_participated_in_hackathons:
        title: Участие в хакатонах
        type: boolean
      has_personal_projects:
        title: Наличие пет-проектов
        type: boolean
      skills_verified:
        title: Навыки подтверждены
        type: boolean
      has_video_presentation:
        title: С видео-презентацией
        type: boolean
      percentage_match:
        title: Percentage match
        type: integer
        readOnly: true
        default: 0
  User:
    required:
      - email
      - username
      - first_name
      - last_name
      - password
    type: object
    properties:
      email:
        title: Электронная почта
        type: string
        format: email
        maxLength: 254
        minLength: 1
      id:
        title: ID
        type: integer
        readOnly: true
      username:
        title: Имя пользователя
        type: string
        maxLength: 150
        minLength: 1
      first_name:
        title: Имя
        type: string
        maxLength: 150
        minLength: 1
      last_name:
        title: Фамилия
        type: string
        maxLength: 150
        minLength: 1
      password:
        title: Password
        type: string
        minLength: 1
  UserCreatePasswordRetype:
    required:
      - username
      - first_name
      - last_name
      - email
      - password
      - re_password
    type: object
    properties:
      username:
        title: Имя пользователя
        type: string
        maxLength: 150
        minLength: 1
      first_name:
        title: Имя
        type: string
        maxLength: 150
        minLength: 1
      last_name:
        title: Фамилия
        type: string
        maxLength: 150
        minLength: 1
      email:
        title: Электронная почта
        type: string
        format: email
        maxLength: 254
        minLength: 1
      id:
        title: ID
        type: integer
        readOnly: true
      password:
        title: Password
        type: string
        minLength: 1
      re_password:
        title: Re password
        type: string
        minLength: 1
  Activation:
    required:
      - uid
      - token
    type: object
    properties:
      uid:
        title: Uid
        type: string
        minLength: 1
      token:
        title: Token
        type: string
        minLength: 1
  SendEmailReset:
    required:
      - email
    type: object
    properties:
      email:
        title: Email
        type: string
        format: email
        minLength: 1
  UsernameResetConfirm:
    required:
      - new_email
    type: object
    properties:
      new_email:
        title: Электронная почта
        type: string
        format: email
        maxLength: 254
        minLength: 1
  PasswordResetConfirm:
    required:
      - uid
      - token
      - new_password
    type: object
    properties:
      uid:
        title: Uid
        type: string
        minLength: 1
      token:
        title: Token
        type: string
        minLength: 1
      new_password:
        title: New password
        type: string
        minLength: 1
  SetUsername:
    required:
      - current_password
      - new_email
    type: object
    properties:
      current_password:
        title: Current password
        type: string
        minLength: 1
      new_email:
        title: Электронная почта
        type: string
        format: email
        maxLength: 254
        minLength: 1
  SetPasswordRetype:
    required:
      - new_password
      - re_new_password
      - current_password
    type: object
    properties:
      new_password:
        title: New password
        type: string
        minLength: 1
      re_new_password:
        title: Re new password
        type: string
        minLength: 1
      current_password:
        title: Current password
        type: string
        minLength: 1
